/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordleRouteImport } from './routes/wordle'
import { Route as WebGamesRouteImport } from './routes/web-games'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as MyTypeRouteImport } from './routes/my-type'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as IndexRouteImport } from './routes/index'

const WordleRoute = WordleRouteImport.update({
  id: '/wordle',
  path: '/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const WebGamesRoute = WebGamesRouteImport.update({
  id: '/web-games',
  path: '/web-games',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTypeRoute = MyTypeRouteImport.update({
  id: '/my-type',
  path: '/my-type',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/my-type': typeof MyTypeRoute
  '/not-found': typeof NotFoundRoute
  '/shopping-list': typeof ShoppingListRoute
  '/web-games': typeof WebGamesRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/my-type': typeof MyTypeRoute
  '/not-found': typeof NotFoundRoute
  '/shopping-list': typeof ShoppingListRoute
  '/web-games': typeof WebGamesRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manifesto': typeof ManifestoRoute
  '/my-type': typeof MyTypeRoute
  '/not-found': typeof NotFoundRoute
  '/shopping-list': typeof ShoppingListRoute
  '/web-games': typeof WebGamesRoute
  '/wordle': typeof WordleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifesto'
    | '/my-type'
    | '/not-found'
    | '/shopping-list'
    | '/web-games'
    | '/wordle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifesto'
    | '/my-type'
    | '/not-found'
    | '/shopping-list'
    | '/web-games'
    | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/manifesto'
    | '/my-type'
    | '/not-found'
    | '/shopping-list'
    | '/web-games'
    | '/wordle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManifestoRoute: typeof ManifestoRoute
  MyTypeRoute: typeof MyTypeRoute
  NotFoundRoute: typeof NotFoundRoute
  ShoppingListRoute: typeof ShoppingListRoute
  WebGamesRoute: typeof WebGamesRoute
  WordleRoute: typeof WordleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordle': {
      id: '/wordle'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-games': {
      id: '/web-games'
      path: '/web-games'
      fullPath: '/web-games'
      preLoaderRoute: typeof WebGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-type': {
      id: '/my-type'
      path: '/my-type'
      fullPath: '/my-type'
      preLoaderRoute: typeof MyTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManifestoRoute: ManifestoRoute,
  MyTypeRoute: MyTypeRoute,
  NotFoundRoute: NotFoundRoute,
  ShoppingListRoute: ShoppingListRoute,
  WebGamesRoute: WebGamesRoute,
  WordleRoute: WordleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
