/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordleRouteImport } from './routes/wordle'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as RealTalkRouteImport } from './routes/real-talk'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as MyTypeRouteImport } from './routes/my-type'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as EqRouteImport } from './routes/eq'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'

const WordleRoute = WordleRouteImport.update({
  id: '/wordle',
  path: '/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const RealTalkRoute = RealTalkRouteImport.update({
  id: '/real-talk',
  path: '/real-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTypeRoute = MyTypeRouteImport.update({
  id: '/my-type',
  path: '/my-type',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const EqRoute = EqRouteImport.update({
  id: '/eq',
  path: '/eq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/eq': typeof EqRoute
  '/manifesto': typeof ManifestoRoute
  '/my-type': typeof MyTypeRoute
  '/not-found': typeof NotFoundRoute
  '/projects': typeof ProjectsRoute
  '/real-talk': typeof RealTalkRoute
  '/shopping-list': typeof ShoppingListRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/eq': typeof EqRoute
  '/manifesto': typeof ManifestoRoute
  '/my-type': typeof MyTypeRoute
  '/not-found': typeof NotFoundRoute
  '/projects': typeof ProjectsRoute
  '/real-talk': typeof RealTalkRoute
  '/shopping-list': typeof ShoppingListRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/eq': typeof EqRoute
  '/manifesto': typeof ManifestoRoute
  '/my-type': typeof MyTypeRoute
  '/not-found': typeof NotFoundRoute
  '/projects': typeof ProjectsRoute
  '/real-talk': typeof RealTalkRoute
  '/shopping-list': typeof ShoppingListRoute
  '/wordle': typeof WordleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/eq'
    | '/manifesto'
    | '/my-type'
    | '/not-found'
    | '/projects'
    | '/real-talk'
    | '/shopping-list'
    | '/wordle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/eq'
    | '/manifesto'
    | '/my-type'
    | '/not-found'
    | '/projects'
    | '/real-talk'
    | '/shopping-list'
    | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/eq'
    | '/manifesto'
    | '/my-type'
    | '/not-found'
    | '/projects'
    | '/real-talk'
    | '/shopping-list'
    | '/wordle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  EqRoute: typeof EqRoute
  ManifestoRoute: typeof ManifestoRoute
  MyTypeRoute: typeof MyTypeRoute
  NotFoundRoute: typeof NotFoundRoute
  ProjectsRoute: typeof ProjectsRoute
  RealTalkRoute: typeof RealTalkRoute
  ShoppingListRoute: typeof ShoppingListRoute
  WordleRoute: typeof WordleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordle': {
      id: '/wordle'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-talk': {
      id: '/real-talk'
      path: '/real-talk'
      fullPath: '/real-talk'
      preLoaderRoute: typeof RealTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-type': {
      id: '/my-type'
      path: '/my-type'
      fullPath: '/my-type'
      preLoaderRoute: typeof MyTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eq': {
      id: '/eq'
      path: '/eq'
      fullPath: '/eq'
      preLoaderRoute: typeof EqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  EqRoute: EqRoute,
  ManifestoRoute: ManifestoRoute,
  MyTypeRoute: MyTypeRoute,
  NotFoundRoute: NotFoundRoute,
  ProjectsRoute: ProjectsRoute,
  RealTalkRoute: RealTalkRoute,
  ShoppingListRoute: ShoppingListRoute,
  WordleRoute: WordleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
